// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqmmwywyggaxbwvqicoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxbW13eXd5Z2dheGJ3dnFpY296Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4NzM5MjgsImV4cCI6MjA1NTQ0OTkyOH0.6G-JkAzjY8sCzAE9ia8zTcQJ2uHm8xeyf_-JMWAiDi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);